name: Test And Publish

on:
  workflow_dispatch:  
  push:
    branches:
    - main
    - master


jobs:
  publish:
    name: publish
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./CapitalClue.sln
        
      - name: Build
        run: dotnet build ./CapitalClue.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./CapitalClue.sln --configuration Release --no-build

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.capitalclue }}
          publish-profile: ${{ ./capitalclue.PublishSettings }}
          package: ${{ capitalclue.scm.azurewebsites.net:443 }}
