name: Test And Publish

on:
  workflow_dispatch:  
  push:
    branches:
    - main
    
env:
  AZURE_WEBAPP_NAME: capitalclue
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    name: publish
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./CapitalClue.sln
        
      - name: Build
        run: dotnet build ./CapitalClue.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test -c Release --no-build
        
      - name: Publish
        run: dotnet publish ./CapitalClue.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
