name: Test And Publish

on:
  workflow_dispatch:  
  push:
    branches:
    - master
    - main



jobs:
  publish:
    name: publish
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./SmallAPI.sln
        
      - name: Build
        run: dotnet build ./SmallAPI.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build
        
      - name: Publish
        run: dotnet publish ./SmallAPI.sln --configuration Release --no-build
